# Generated by Django 6.0.3 on 2026-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
